export { default as Anchor } from 'component-library/src/components/Anchor/Anchor.component'
export { default as Button } from 'component-library/src/components/Button/Button.component'
export { default as FlexBox } from 'component-library/src/components/FlexBox/FlexBox.component'
export { default as Box } from 'component-library/src/components/Box/Box.component'
export { default as Text } from 'component-library/src/components/Text/Text.component'
